[package]
name = "bridgy_followers"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
atrium-api = "0.25"
atrium-common = "0.1"
atrium-xrpc-client = "0.5"
clap = { version = "4.0", features = ["derive"] }
color-eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tokio = { version = "1.0", features = ["full"] }
